version: '2'
services:
  study-force:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      - .:/web:delegated
    ports:
      - 7000:7000
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "7001:8080"
    volumes:
      - ./docs/swagger/:/swagger
    environment:
      SWAGGER_JSON: /swagger/api/index.yml
